language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip uninstall setuptools
  - pip install setuptools
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
  - CYTHONIZE=1 ./setup.py build
# command to run tests
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pytest