# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

strategy:
  matrix:
    Linux_Python36:
      VM_IMAGE: 'ubuntu-16.04'
      PYTHON_VERSION: '3.6'
    Linux_Python37:
      VM_IMAGE: 'ubuntu-16.04'
      PYTHON_VERSION: '3.7'
    Linux_Python38:
      VM_IMAGE: 'ubuntu-16.04'
      PYTHON_VERSION: '3.8'
    Windows_Python36:
      VM_IMAGE: 'vs2017-win2016'
      PYTHON_VERSION: '3.6'
    Windows_Python37:
      VM_IMAGE: 'vs2017-win2016'
      PYTHON_VERSION: '3.7'
    Windows_Python38:
      VM_IMAGE: 'vs2017-win2016'
      PYTHON_VERSION: '3.8'
    MacOS_Python36:
      VM_IMAGE: 'macos-10.14'
      PYTHON_VERSION: '3.6'
    MacOS_Python37:
      VM_IMAGE: 'macos-10.14'
      PYTHON_VERSION: '3.7'
    MacOS_Python38:
      VM_IMAGE: 'macos-10.14'
      PYTHON_VERSION: '3.8'

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install dependencies'

- script: |
    python setup.py build bdist_wheel sdist
  displayName: 'build wheel and sdist'

# Publish pipeline artifacts
# Publish (upload) a file or directory as a named artifact for the current run
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'dist'

