# From: https://cibuildwheel.readthedocs.io/en/stable/setup/#azure-pipelines

variables:
- name: CIBW_BUILD
  value: cp36-*_x86_64 cp37-*_x86_64 cp38-*_x86_64
#- name: CIBW_BEFORE_TEST
#  value: pip install -r requirements-dev.txt
#- name: CIBW_TEST_COMMAND
#  value: pytest {package}/tests


jobs:
- job: macos
  pool: {vmImage: 'macOS-10.15'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        python3 -m pip install --upgrade pip
        pip3 install cibuildwheel==1.4.2
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
    - bash: |
        python -c "from k_means_constrained import KMeansConstrained; import numpy as np; clf=KMeansConstrained(1,1,1);clf.fit(np.array([[0,0]]));"

#- job: linux
#  pool: {vmImage: 'Ubuntu-16.04'}
#  steps:
#    - task: UsePythonVersion@0
#    - bash: |
#        python3 -m pip install --upgrade pip
#        pip3 install cibuildwheel==1.4.2
#        cibuildwheel --output-dir wheelhouse .
#    - task: PublishBuildArtifacts@1
#      inputs: {pathtoPublish: 'wheelhouse'}
#    - bash: |
#        python -c "from k_means_constrained import KMeansConstrained; import numpy as np; clf=KMeansConstrained(1,1,1);clf.fit(np.array([[0,0]]));"


#
#- job: windows
#  pool: {vmImage: 'vs2017-win2016'}
#  steps:
#    - task: UsePythonVersion@0
#    - script: choco install vcpython27 -f -y
#      displayName: Install Visual C++ for Python 2.7
#    - bash: |
#        python -m pip install --upgrade pip
#        pip install cibuildwheel==1.4.2
#        cibuildwheel --output-dir wheelhouse .
#    - task: PublishBuildArtifacts@1
#      inputs: {pathtoPublish: 'wheelhouse'}